Merge feat/nextjs videos into feat/nextjs
unswwit/backend pull request #15
Opened 2022-06-14 11:51 UTC by Eddyyyh

2022-06-21 07:42 UTC, joanna209 requested changes

2022-06-21 07:52 UTC, Eddyyyh commented on frontend/components/Footer.js
> +    "Join Us": "/joinUs",
done !

2022-06-21 07:59 UTC, Eddyyyh commented on frontend/components/LoadingScreen.js
> +        src={`/walkingWillow.gif`}
done !

2022-06-21 09:39 UTC, Eddyyyh commented on frontend/pages/media/videos.js
> +              <div className={styles.searchBar}>
done !

2022-07-01 12:43 UTC, joanna209 approved these changes

2022-07-01 12:50 UTC, merged